### ISSUE TITLE
HTTP HEAD calls return 405 method not allowed

### ISSUE THREAD

**Issue by Nestorferrando** [toolarium/toolarium-jwebserver#1]
Hi! I'm using your library, I find it quite useful!!, there are not may simple java-based http-servers.

One thing I'm missing is support to HEAD calls in addition to GET. At the moment, I always get an HTTP 405 method not allowed.

I guess it is because the routing in RoutingHandler.java is missing? will it be oossible to implement it?

Thanks!

**Comment by mepux** [comment]
Hi
Best thanks, yes I was searching and could find nothing similar. 
The HEAD operation works on proxy mode but not on delivering resources. It's now fixed in version 1.2.2.
